# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TelaTransfere.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaTransfere(object):
    def setupUi(self, TelaTransfere):
        TelaTransfere.setObjectName("TelaTransfere")
        TelaTransfere.resize(436, 658)
        self.centralwidget = QtWidgets.QWidget(TelaTransfere)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 451, 641))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.user_2 = QtWidgets.QLabel(self.frame)
        self.user_2.setGeometry(QtCore.QRect(170, 40, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.user_2.setFont(font)
        self.user_2.setStyleSheet("color: rgb(192, 97, 203);")
        self.user_2.setObjectName("user_2")
        self.inputvalor = QtWidgets.QLabel(self.frame)
        self.inputvalor.setGeometry(QtCore.QRect(40, 110, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.inputvalor.setFont(font)
        self.inputvalor.setStyleSheet("color: rgb(192, 97, 203);")
        self.inputvalor.setObjectName("inputvalor")
        self.valorTransfere = QtWidgets.QLineEdit(self.frame)
        self.valorTransfere.setGeometry(QtCore.QRect(40, 150, 361, 41))
        self.valorTransfere.setStyleSheet("border-color: rgb(192, 97, 203);\n"
"color: rgb(145, 65, 172);")
        self.valorTransfere.setObjectName("valorTransfere")
        self.cpfDestino = QtWidgets.QLineEdit(self.frame)
        self.cpfDestino.setGeometry(QtCore.QRect(40, 250, 361, 41))
        self.cpfDestino.setStyleSheet("border-color: rgb(192, 97, 203);\n"
"color: rgb(145, 65, 172);")
        self.cpfDestino.setText("")
        self.cpfDestino.setObjectName("cpfDestino")
        self.inputvalor_2 = QtWidgets.QLabel(self.frame)
        self.inputvalor_2.setGeometry(QtCore.QRect(40, 210, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.inputvalor_2.setFont(font)
        self.inputvalor_2.setStyleSheet("color: rgb(192, 97, 203);")
        self.inputvalor_2.setObjectName("inputvalor_2")
        self.btn_transfere = QtWidgets.QPushButton(self.frame)
        self.btn_transfere.setGeometry(QtCore.QRect(30, 480, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_transfere.setFont(font)
        self.btn_transfere.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(145, 65, 172);")
        self.btn_transfere.setObjectName("btn_transfere")
        self.btn_voltar = QtWidgets.QPushButton(self.frame)
        self.btn_voltar.setGeometry(QtCore.QRect(260, 480, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_voltar.setFont(font)
        self.btn_voltar.setStyleSheet("color: rgb(145, 65, 172);\n"
"background-color: rgb(255, 255, 255);")
        self.btn_voltar.setObjectName("btn_voltar")
        TelaTransfere.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(TelaTransfere)
        self.statusbar.setObjectName("statusbar")
        TelaTransfere.setStatusBar(self.statusbar)

        self.retranslateUi(TelaTransfere)
        QtCore.QMetaObject.connectSlotsByName(TelaTransfere)

    def retranslateUi(self, TelaTransfere):
        _translate = QtCore.QCoreApplication.translate
        TelaTransfere.setWindowTitle(_translate("TelaTransfere", "MainWindow"))
        self.user_2.setText(_translate("TelaTransfere", "TRANSFERIR"))
        self.inputvalor.setText(_translate("TelaTransfere", "Digite o valor"))
        self.inputvalor_2.setText(_translate("TelaTransfere", "Numero da Conta"))
        self.btn_transfere.setText(_translate("TelaTransfere", "Transferir"))
        self.btn_voltar.setText(_translate("TelaTransfere", "Voltar"))
