# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TelaDepositar.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaDepositar(object):
    def setupUi(self, TelaDepositar):
        TelaDepositar.setObjectName("TelaDepositar")
        TelaDepositar.resize(474, 655)
        self.centralwidget = QtWidgets.QWidget(TelaDepositar)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 471, 641))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.user_2 = QtWidgets.QLabel(self.frame_2)
        self.user_2.setGeometry(QtCore.QRect(170, 40, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.user_2.setFont(font)
        self.user_2.setStyleSheet("color: rgb(192, 97, 203);")
        self.user_2.setObjectName("user_2")
        self.inputvalor = QtWidgets.QLabel(self.frame_2)
        self.inputvalor.setGeometry(QtCore.QRect(40, 110, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.inputvalor.setFont(font)
        self.inputvalor.setStyleSheet("color: rgb(192, 97, 203);")
        self.inputvalor.setObjectName("inputvalor")
        self.valor_depositar = QtWidgets.QLineEdit(self.frame_2)
        self.valor_depositar.setGeometry(QtCore.QRect(40, 150, 361, 41))
        self.valor_depositar.setStyleSheet("border-color: rgb(192, 97, 203);\n"
"color: rgb(145, 65, 172);")
        self.valor_depositar.setObjectName("valor_depositar")
        self.btn_depositar = QtWidgets.QPushButton(self.frame_2)
        self.btn_depositar.setGeometry(QtCore.QRect(30, 480, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_depositar.setFont(font)
        self.btn_depositar.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(145, 65, 172);")
        self.btn_depositar.setObjectName("btn_depositar")
        self.btn_voltar = QtWidgets.QPushButton(self.frame_2)
        self.btn_voltar.setGeometry(QtCore.QRect(260, 480, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_voltar.setFont(font)
        self.btn_voltar.setStyleSheet("color: rgb(145, 65, 172);\n"
"background-color: rgb(255, 255, 255);")
        self.btn_voltar.setObjectName("btn_voltar")
        TelaDepositar.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(TelaDepositar)
        self.statusbar.setObjectName("statusbar")
        TelaDepositar.setStatusBar(self.statusbar)

        self.retranslateUi(TelaDepositar)
        QtCore.QMetaObject.connectSlotsByName(TelaDepositar)

    def retranslateUi(self, TelaDepositar):
        _translate = QtCore.QCoreApplication.translate
        TelaDepositar.setWindowTitle(_translate("TelaDepositar", "MainWindow"))
        self.user_2.setText(_translate("TelaDepositar", "DEPOSITAR"))
        self.inputvalor.setText(_translate("TelaDepositar", "Digite o valor"))
        self.btn_depositar.setText(_translate("TelaDepositar", "Depositar"))
        self.btn_voltar.setText(_translate("TelaDepositar", "Voltar"))
