# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TelaSacar.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaSacar(object):
    def setupUi(self, TelaSacar):
        TelaSacar.setObjectName("TelaSacar")
        TelaSacar.resize(452, 660)
        self.centralwidget = QtWidgets.QWidget(TelaSacar)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 471, 631))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 451, 641))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.user_2 = QtWidgets.QLabel(self.frame_2)
        self.user_2.setGeometry(QtCore.QRect(170, 40, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.user_2.setFont(font)
        self.user_2.setStyleSheet("color: rgb(192, 97, 203);")
        self.user_2.setObjectName("user_2")
        self.inputvalor = QtWidgets.QLabel(self.frame_2)
        self.inputvalor.setGeometry(QtCore.QRect(40, 110, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.inputvalor.setFont(font)
        self.inputvalor.setStyleSheet("color: rgb(192, 97, 203);")
        self.inputvalor.setObjectName("inputvalor")
        self.valor_Sacar = QtWidgets.QLineEdit(self.frame_2)
        self.valor_Sacar.setGeometry(QtCore.QRect(40, 150, 361, 41))
        self.valor_Sacar.setStyleSheet("border-color: rgb(192, 97, 203);\n"
"color: rgb(145, 65, 172);")
        self.valor_Sacar.setObjectName("valor_Sacar")
        self.btn_sacar = QtWidgets.QPushButton(self.frame_2)
        self.btn_sacar.setGeometry(QtCore.QRect(30, 480, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_sacar.setFont(font)
        self.btn_sacar.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(145, 65, 172);")
        self.btn_sacar.setObjectName("btn_sacar")
        self.btn_voltar = QtWidgets.QPushButton(self.frame_2)
        self.btn_voltar.setGeometry(QtCore.QRect(260, 480, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_voltar.setFont(font)
        self.btn_voltar.setStyleSheet("color: rgb(145, 65, 172);\n"
"background-color: rgb(255, 255, 255);")
        self.btn_voltar.setObjectName("btn_voltar")
        TelaSacar.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(TelaSacar)
        self.statusbar.setObjectName("statusbar")
        TelaSacar.setStatusBar(self.statusbar)

        self.retranslateUi(TelaSacar)
        QtCore.QMetaObject.connectSlotsByName(TelaSacar)

    def retranslateUi(self, TelaSacar):
        _translate = QtCore.QCoreApplication.translate
        TelaSacar.setWindowTitle(_translate("TelaSacar", "MainWindow"))
        self.user_2.setText(_translate("TelaSacar", "SACAR"))
        self.inputvalor.setText(_translate("TelaSacar", "Digite o valor"))
        self.btn_sacar.setText(_translate("TelaSacar", "Sacar"))
        self.btn_voltar.setText(_translate("TelaSacar", "Voltar"))
