# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TelaExtrato.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaExtrato(object):
    def setupUi(self, TelaExtrato):
        TelaExtrato.setObjectName("TelaExtrato")
        TelaExtrato.resize(472, 672)
        self.centralwidget = QtWidgets.QWidget(TelaExtrato)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 481, 651))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.extrtolabel = QtWidgets.QLabel(self.frame_2)
        self.extrtolabel.setGeometry(QtCore.QRect(180, 40, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.extrtolabel.setFont(font)
        self.extrtolabel.setStyleSheet("color: rgb(192, 97, 203);")
        self.extrtolabel.setObjectName("extrtolabel")
        self.btn_voltar = QtWidgets.QPushButton(self.frame_2)
        self.btn_voltar.setGeometry(QtCore.QRect(270, 580, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_voltar.setFont(font)
        self.btn_voltar.setStyleSheet("color: rgb(145, 65, 172);\n"
"background-color: rgb(255, 255, 255);")
        self.btn_voltar.setObjectName("btn_voltar")
        self.textEdit = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit.setGeometry(QtCore.QRect(30, 110, 401, 421))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("color: rgb(145, 65, 172);\n"
"background-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        TelaExtrato.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(TelaExtrato)
        self.statusbar.setObjectName("statusbar")
        TelaExtrato.setStatusBar(self.statusbar)

        self.retranslateUi(TelaExtrato)
        QtCore.QMetaObject.connectSlotsByName(TelaExtrato)

    def retranslateUi(self, TelaExtrato):
        _translate = QtCore.QCoreApplication.translate
        TelaExtrato.setWindowTitle(_translate("TelaExtrato", "MainWindow"))
        self.extrtolabel.setText(_translate("TelaExtrato", "EXTRATO"))
        self.btn_voltar.setText(_translate("TelaExtrato", "Voltar"))
