-- MySQL Script generated by MySQL Workbench
-- seg 23 jan 2023 19:43:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema banco
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `banco` ;

-- -----------------------------------------------------
-- Schema banco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banco` ;
USE `banco` ;

-- -----------------------------------------------------
-- Table `banco`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banco`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `banco`.`Cliente` (
  `IdCliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`IdCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco`.`Conta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banco`.`Conta` ;

CREATE TABLE IF NOT EXISTS `banco`.`Conta` (
  `idConta` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NOT NULL,
  `saldo` FLOAT NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `Cliente_IdCliente` INT NOT NULL,
  PRIMARY KEY (`idConta`),
  INDEX `fk_Conta_Cliente_idx` (`Cliente_IdCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Conta_Cliente`
    FOREIGN KEY (`Cliente_IdCliente`)
    REFERENCES `banco`.`Cliente` (`IdCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco`.`Historico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banco`.`Historico` ;

CREATE TABLE IF NOT EXISTS `banco`.`Historico` (
  `idHistorico` INT NOT NULL AUTO_INCREMENT,
  `data` VARCHAR(25) NOT NULL,
  `operacao` VARCHAR(45) NOT NULL,
  `Conta_idConta` INT NOT NULL,
  PRIMARY KEY (`idHistorico`),
  INDEX `fk_Historico_Conta1_idx` (`Conta_idConta` ASC) VISIBLE,
  CONSTRAINT `fk_Historico_Conta1`
    FOREIGN KEY (`Conta_idConta`)
    REFERENCES `banco`.`Conta` (`idConta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
